### ISSUE TITLE
Nest can't resolve dependencies of the UserController

### ISSUE THREAD

**Issue by amitp-gc** [bhagyajitjagdev/nestjs-email#1]
<img width="1763" alt="image" src="https://github.com/bhagyajitjagdev/nestjs-email/assets/87794694/6e702a70-d141-473c-9404-e7b95738010e">

**Comment by amitp-gc** [comment]
@bhagyajitjagdev Kindly suggest !

**Comment by bhagyajitjagdev** [comment]
> @bhagyajitjagdev Kindly suggest !

![image](https://github.com/bhagyajitjagdev/nestjs-email/assets/66861049/24a441d3-80f6-4927-b572-af678179e216)

add `TypedEventEmitterModule` to the `app.module.ts` imports

as `TypedEventEmitterModule` is tagged with a global decorator you dont have to import it in every module just add it to the `app.module.ts` and it will be available throughout the project

___already fixed the code take a pull, it should resolve the issue___

**Comment by amitp-gc** [comment]
Thanks
